### ISSUE TITLE
Error compiling Makefile.Pi.OLED

### ISSUE THREAD

**Issue by ok2it** [g4klx/MMDVMHost#178]
Latest git pull and OLED wont work (wont compile).

i tested Oled LIBs and ArduiPi_OLED.....libs work ok.

g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -L/usr/locacl/lib -c -o MMDVMHost.o MMDVMHost.cpp
MMDVMHost.cpp: In member function ‘void CMMDVMHost::createDisplay()’:
MMDVMHost.cpp:1076:70: error: invalid new-expression of abstract class type ‘COLED’
   m_display = new COLED(displayType, displayBrightness, displayInvert);
                                                                      ^
In file included from MMDVMHost.cpp:40:0:
OLED.h:75:7: note:   because the following virtual functions are pure within ‘COLED’:
 class COLED : public CDisplay
       ^
In file included from MMDVMHost.h:27:0,
                 from MMDVMHost.cpp:19:
Display.h:74:15: note:  virtual void CDisplay::writeCWInt()
  virtual void writeCWInt() = 0;
               ^
Display.h:75:15: note:  virtual void CDisplay::clearCWInt()
  virtual void clearCWInt() = 0;
               ^
In file included from MMDVMHost.cpp:40:0:
OLED.h: At global scope:
OLED.h:37:22: warning: ‘logo_glcd_bmp’ defined but not used [-Wunused-variable]
 static unsigned char logo_glcd_bmp[] =
                      ^
OLED.h:56:22: warning: ‘logo_dmr_bmp’ defined but not used [-Wunused-variable]
 static unsigned char logo_dmr_bmp[] =
                      ^
Makefile.Pi.OLED:23: recipe for target 'MMDVMHost.o' failed
make: *** [MMDVMHost.o] Error 1
root@raspberrypi:/home/pi/MMDVMHost# ~

**Comment by phl0** [comment]
I quote my post to the MMDVM group from a few minutes ago:

--- %< ---
Hi,

seems like I installed the error into MMDVMHost. I already corrected it
in my dev branch. You can pull the OLED.h from here:

https://github.com/phl0/MMDVMHost/tree/dev

It compiles (with two warnings) here but I cannot test it due to not
having an OLED display. Could you please test and report here?

Its already prepared for being pulled into Jonathan repo.

vy73 de Florian DF2ET
--- %< ---

**Comment by phl0** [comment]
It was merged into the main code 2 minutes ago. Please update your git repo and re-compile.

**Comment by ok2it** [comment]
Yes works ok.
Tnx
Jiri

**Comment by phl0** [comment]
Could you please close this issue then?

**Comment by ok2it** [comment]
Hi Flo

Sorry I made mistake last night and I compiled it on old Raspberry with older version of mmdvmhost (no P25 version).

I still get OLED compile errors:

g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o MMDVMHost.o MMDVMHost.cpp
In file included from MMDVMHost.cpp:40:0:
OLED.h:37:22: warning: ‘logo_glcd_bmp’ defined but not used [-Wunused-variable]
 static unsigned char logo_glcd_bmp[] =
                      ^
OLED.h:56:22: warning: ‘logo_dmr_bmp’ defined but not used [-Wunused-variable]
 static unsigned char logo_dmr_bmp[] =
                      ^
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o Modem.o Modem.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o ModemSerialPort.o ModemSerialPort.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o Mutex.o Mutex.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o Nextion.o Nextion.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o NullDisplay.o NullDisplay.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o P25Audio.o P25Audio.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o P25Control.o P25Control.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o P25Data.o P25Data.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o P25LowSpeedData.o P25LowSpeedData.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o P25Network.o P25Network.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o P25NID.o P25NID.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o P25Utils.o P25Utils.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o QR1676.o QR1676.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o RS129.o RS129.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o RS241213.o RS241213.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o SerialController.o SerialController.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o SerialPort.o SerialPort.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o SHA256.o SHA256.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o StopWatch.o StopWatch.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o Sync.o Sync.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o TFTSerial.o TFTSerial.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o Thread.o Thread.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o Timer.o Timer.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o UDPSocket.o UDPSocket.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o Utils.o Utils.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o YSFControl.o YSFControl.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o YSFConvolution.o YSFConvolution.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o YSFFICH.o YSFFICH.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o YSFNetwork.o YSFNetwork.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -c -o YSFPayload.o YSFPayload.cpp
g++ AMBEFEC.o BCH.o BPTC19696.o Conf.o CRC.o Display.o DMRControl.o DMRCSBK.o DMRData.o DMRDataHeader.o DMREMB.o DMREmbeddedLC.o DMRFullLC.o DMRLookup.o DMRLC.o DMRNetwork.o DMRShortLC.o DMRSlot.o DMRSlotType.o DMRAccessControl.o DMRTrellis.o DStarControl.o DStarHeader.o DStarNetwork.o DStarSlowData.o Golay2087.o Golay24128.o Hamming.o OLED.o Log.o MMDVMHost.o Modem.o ModemSerialPort.o Mutex.o Nextion.o NullDisplay.o P25Audio.o P25Control.o P25Data.o P25LowSpeedData.o P25Network.o P25NID.o P25Utils.o QR1676.o RS129.o RS241213.o SerialController.o SerialPort.o SHA256.o StopWatch.o Sync.o TFTSerial.o Thread.o Timer.o UDPSocket.o Utils.o YSFControl.o YSFConvolution.o YSFFICH.o YSFNetwork.o YSFPayload.o -g -O3 -Wall -std=c++0x -pthread -DOLED -I/usr/local/include -lArduiPi_OLED -lpthread -o MMDVMHost
OLED.o:(.rodata+0x44): undefined reference to `COLED::writeCWInt()'
OLED.o:(.rodata+0x48): undefined reference to `COLED::clearCWInt()'
collect2: error: ld returned 1 exit status
Makefile.Pi.OLED:19: recipe for target 'MMDVMHost' failed
make: *** [MMDVMHost] Error 1
root@raspberrypi:/home/pi/M1/MMDVMHost#

**Comment by phl0** [comment]
I will look into it again. It compiled cleanly on my Raspi with the
latest MMDVMHost. Did you compile with "make -f Makefile.Pi.OLED"?
Probably a "make clean" before ...

**Comment by ok2it** [comment]
Hi Flo


Yes….see bellow if it helps….

I made clean folder (mkdir M1) and then cloned later git…. g4klx/MMDVMHost
Tested OLED using command prompt so all libs are working and installed
Tested OLED using older MMDVMHost, works ok
Compiled
root@raspberrypi:/home/pi/M1/MMDVMHost# make clean -f Makefile.Pi.OLED 
rm -f MMDVMHost *.o *.d *.bak *~


root@raspberrypi:/home/pi/M1/MMDVMHost# make all -f Makefile.Pi.OLED 
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o AMBEFEC.o AMBEFEC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o BCH.o BCH.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o BPTC19696.o BPTC19696.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o Conf.o Conf.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o CRC.o CRC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o Display.o Display.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DMRControl.o DMRControl.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DMRCSBK.o DMRCSBK.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DMRData.o DMRData.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DMRDataHeader.o DMRDataHeader.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DMREMB.o DMREMB.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DMREmbeddedLC.o DMREmbeddedLC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DMRFullLC.o DMRFullLC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DMRLookup.o DMRLookup.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DMRLC.o DMRLC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DMRNetwork.o DMRNetwork.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DMRShortLC.o DMRShortLC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DMRSlot.o DMRSlot.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DMRSlotType.o DMRSlotType.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DMRAccessControl.o DMRAccessControl.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DMRTrellis.o DMRTrellis.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DStarControl.o DStarControl.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DStarHeader.o DStarHeader.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DStarNetwork.o DStarNetwork.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o DStarSlowData.o DStarSlowData.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o Golay2087.o Golay2087.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o Golay24128.o Golay24128.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o Hamming.o Hamming.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o OLED.o OLED.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o Log.o Log.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o MMDVMHost.o MMDVMHost.cpp
In file included from MMDVMHost.cpp:40:0:
OLED.h:37:22: warning: ‘logo_glcd_bmp’ defined but not used [-Wunused-variable]
 static unsigned char logo_glcd_bmp[] =
                      ^
OLED.h:56:22: warning: ‘logo_dmr_bmp’ defined but not used [-Wunused-variable]
 static unsigned char logo_dmr_bmp[] =
                      ^
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o Modem.o Modem.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o ModemSerialPort.o ModemSerialPort.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o Mutex.o Mutex.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o Nextion.o Nextion.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o NullDisplay.o NullDisplay.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o P25Audio.o P25Audio.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o P25Control.o P25Control.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o P25Data.o P25Data.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o P25LowSpeedData.o P25LowSpeedData.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o P25Network.o P25Network.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o P25NID.o P25NID.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o P25Utils.o P25Utils.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o QR1676.o QR1676.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o RS129.o RS129.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o RS241213.o RS241213.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o SerialController.o SerialController.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o SerialPort.o SerialPort.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o SHA256.o SHA256.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o StopWatch.o StopWatch.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o Sync.o Sync.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o TFTSerial.o TFTSerial.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o Thread.o Thread.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o Timer.o Timer.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o UDPSocket.o UDPSocket.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o Utils.o Utils.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o YSFControl.o YSFControl.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o YSFConvolution.o YSFConvolution.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o YSFFICH.o YSFFICH.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o YSFNetwork.o YSFNetwork.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -c -o YSFPayload.o YSFPayload.cpp
g++ AMBEFEC.o BCH.o BPTC19696.o Conf.o CRC.o Display.o DMRControl.o DMRCSBK.o DMRData.o DMRDataHeader.o DMREMB.o DMREmbeddedLC.o DMRFullLC.o DMRLookup.o DMRLC.o DMRNetwork.o DMRShortLC.o DMRSlot.o DMRSlotType.o DMRAccessControl.o DMRTrellis.o DStarControl.o DStarHeader.o DStarNetwork.o DStarSlowData.o Golay2087.o Golay24128.o Hamming.o OLED.o Log.o MMDVMHost.o Modem.o ModemSerialPort.o Mutex.o Nextion.o NullDisplay.o P25Audio.o P25Control.o P25Data.o P25LowSpeedData.o P25Network.o P25NID.o P25Utils.o QR1676.o RS129.o RS241213.o SerialController.o SerialPort.o SHA256.o StopWatch.o Sync.o TFTSerial.o Thread.o Timer.o UDPSocket.o Utils.o YSFControl.o YSFConvolution.o YSFFICH.o YSFNetwork.o YSFPayload.o -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -lArduiPi_OLED -lpthread -lwiringPi -o MMDVMHost
OLED.o:(.rodata+0x44): undefined reference to `COLED::writeCWInt()'
OLED.o:(.rodata+0x48): undefined reference to `COLED::clearCWInt()'
collect2: error: ld returned 1 exit status
Makefile.Pi.OLED:19: recipe for target 'MMDVMHost' failed
make: *** [MMDVMHost] Error 1
root@raspberrypi:/home/pi/M1/MMDVMHost# make all -f Makefile.Pi.OLED -i
g++ AMBEFEC.o BCH.o BPTC19696.o Conf.o CRC.o Display.o DMRControl.o DMRCSBK.o DMRData.o DMRDataHeader.o DMREMB.o DMREmbeddedLC.o DMRFullLC.o DMRLookup.o DMRLC.o DMRNetwork.o DMRShortLC.o DMRSlot.o DMRSlotType.o DMRAccessControl.o DMRTrellis.o DStarControl.o DStarHeader.o DStarNetwork.o DStarSlowData.o Golay2087.o Golay24128.o Hamming.o OLED.o Log.o MMDVMHost.o Modem.o ModemSerialPort.o Mutex.o Nextion.o NullDisplay.o P25Audio.o P25Control.o P25Data.o P25LowSpeedData.o P25Network.o P25NID.o P25Utils.o QR1676.o RS129.o RS241213.o SerialController.o SerialPort.o SHA256.o StopWatch.o Sync.o TFTSerial.o Thread.o Timer.o UDPSocket.o Utils.o YSFControl.o YSFConvolution.o YSFFICH.o YSFNetwork.o YSFPayload.o -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -DOLED -I/usr/local/include -I/usr/local/lib -lArduiPi_OLED -lpthread -lwiringPi -o MMDVMHost
OLED.o:(.rodata+0x44): undefined reference to `COLED::writeCWInt()'
OLED.o:(.rodata+0x48): undefined reference to `COLED::clearCWInt()'
collect2: error: ld returned 1 exit status
Makefile.Pi.OLED:19: recipe for target 'MMDVMHost' failed
make: [MMDVMHost] Error 1 (ignored)

**Comment by phl0** [comment]
Ok, confirmed:

OLED.o:(.rodata+0x44): undefined reference to `COLED::writeCWInt()'
OLED.o:(.rodata+0x48): undefined reference to `COLED::clearCWInt()'
collect2: error: ld returned 1 exit status
Makefile.Pi.OLED:19: recipe for target 'MMDVMHost' failed
make: *** [MMDVMHost] Error 1

Interesting that this did not show up yesterday. Maybe I forgot to "make
clean" before.

**Comment by phl0** [comment]
Ok, adding the procedures just to the headers files is not sufficient. I
created the two procedures in the C sources now but they are empty. Now
it compiles after a make clean here. Could you please try again with the
OLED.cpp from my repo:

https://github.com/phl0/MMDVMHost/tree/devel

In the meatime I will look to fill these with content.

**Comment by g4klx** [comment]
Don't worry about content for me just yet. Could you put up a pull request with the compiling but does nothing versions so I can do an official release as soon as possible.

**Comment by g4klx** [comment]
Unless you can make it do something useful by Friday afternoon at the latest.

**Comment by ok2it** [comment]
Yes Flo,

I pulled just OLED.cpp and it works ok. It really seems that adding props.to OLED.h won’t help.

I quit programming when 10-11 under GW-BASIC,COBOL and bit of 8bit Turbo Assembler haha.
I admire you lot for making MMDVM real-deal. Fantastic work.
I

**Comment by phl0** [comment]
I just pushed two more commits to my devel branch. That should enable
displaying a string "CW TX" if CW is actually transmitted. Could you
please test that? I don't have an OLED display ... Sri
If there are any more errors please give a pic or a video. You can set
the CW time to one minute for testing purposes.

**Comment by ok2it** [comment]
Sorry to sound stupid… what git command do i have to use to select the level.branch commit??

I have a separate cloned repo of:
https://github.com/phl0/MMDVMHost.git
When compiled as is I get same error as before so obviously I haven’t selected the correct level branch… hints how to ?  Git branch origin….???

**Comment by phl0** [comment]
So you have checked out my fork. In that directory you can do a "git
checkout devel" to switch to the devel branch.

You currently get an arror because the code is not in the master branch
yet. I want wo wait with the merge into master until you successfully
tested my code.

**Comment by ok2it** [comment]
So compile is Ok. Works but might need refresh or CLR screen as it adds CW on top of Idle. See attachment.

Jiri

But original no compile issue would be fixed with this commit.


J.


Kindly


Jiří Čulák

Presales Engineer

FourteenIP EU - Czech republic

Tel +420 22888 0370

Mob +420 731 611577






On Thu, Oct 20, 2016 at 11:59 AM +0200, "Florian (DF2ET)" <notifications@github.com> wrote:





So you have checked out my fork. In that directory you can do a "git
checkout devel" to switch to the devel branch.

You currently get an arror because the code is not in the master branch
yet. I want wo wait with the merge into master until you successfully
tested my code.

**Comment by phl0** [comment]
Seems like the attachment was stripped of. Could you please upload the
pic on github direclty?

**Comment by ok2it** [comment]
![oled 1](https://cloud.githubusercontent.com/assets/22943285/19556986/07dcfb46-96c4-11e6-9433-b3e41074782f.jpg)

**Comment by g4klx** [comment]
Pretty!

**Comment by phl0** [comment]
Okay and it happens when is goes from CW back to Idle I guess?

**Comment by phl0** [comment]
Ok, seems like it also happens when going from Idle to CW. I made another commit and inserted two cleardisplay commands. Could you please update your clone of my devel branch and re-test?

**Comment by ok2it** [comment]
Hmm…seems yes and also vice-versa.

Also, when DMR logo is displayed with:

1.Listening
2.Listening

When Fusion kicks in (network voice traffic initiated at remote YSF GW) it Displays FUSION and N OK2IT  ALL  on second line and on third line,
I still see * 2.Listening *from DMR time….
BTW I use nonane I2C OLEDdisplay…


PS – just tested:  IDLE looks OK, then CW ID gets added on top of Idle screen, and when it goes back to Idle, it keep displaying the mishmash…until there is traffic, local or net.
Might be worth adding a init/clear sequence infront of every “change” in whats being displayed??

**Comment by phl0** [comment]
Did you test my latest commit https://github.com/phl0/MMDVMHost/commit/87de3105c2437053d46e0f27469e2a79587cbcd4 ? I added a cleardisplay that ought to clear it ... Maybe it needs a display.display after the clear?

**Comment by phl0** [comment]
diff --git a/OLED.cpp b/OLED.cpp
index 7421ced..3885341 100644
--- a/OLED.cpp
+++ b/OLED.cpp
@@ -236,6 +236,7 @@ void COLED::clearP25Int()
 void COLED::writeCWInt()
 {
     display.clearDisplay();
+    display.display();
     display.setCursor(0,display.height()/2);
     display.setTextSize(3);
     display.print("CW TX");
@@ -247,6 +248,7 @@ void COLED::writeCWInt()
 void COLED::clearCWInt()
 {
     display.clearDisplay();
+    display.display();
     display.setCursor(0,display.height()/2);
     display.setTextSize(3);
     display.print("Idle");

Could you please test this?

**Comment by ok2it** [comment]
Sure I will. I am now on road/driving. 
I will test once back.
Thanks for super-quick responses!

**Comment by phl0** [comment]
No problem at all. Would like to have that closed before @G4KLX makes the next release tomorrow.

**Comment by ok2it** [comment]
One more item I have spotted you might want doublecheck on OLED....

When MMDVMHost is idle and receives YSF Network transmission it displays it as DMR first (if DMR is enabled on MMDVM). 
I can confirmtah even when DMR is displayed it is actually YSF whats being transmitted.

Jiri

**Comment by g4klx** [comment]
It was written by Rudy from BrandMeister with only DMR in mind. I think I added the other modes, blind. So no surprise that it doesn't work properly. My main concern is at least to get it compiling. Actually doing anything meaningful comes later :-)

**Comment by ok2it** [comment]
In that case i guess we can close the …Error Compiling…. As I can compile now ok and move this to other thread at lower importance.

Would it be preferred method?
J

**Comment by g4klx** [comment]
That's fine. How about a cut off of 1800 UTC tomorrow?

**Comment by phl0** [comment]
Fine for me as I have to be off to the club meeting then :-)

@ok2it Would you be able to test at least the Idle/CW Tx transition until then?

**Comment by ok2it** [comment]
Latest phl0 commit from devel branch is:
Compiling OK
Displaying CW and Idle OK

I am closing the issue and thanks all for great work!

**Comment by ok2it** [comment]
Features set

1.Priorities of incoming stream (DMR-Fusion-D*)
2. DTMF Decoder with option to call shell script or to change setting
3. LED – instead of OLED and LCD, use GPIO and 4 LEDs to display status
(all 4 LEDs -  IDLE so avial.for all modes.   Each LED to indicate both RX,TX and ModeHang.  Simple but useful when used as rptr on hilltop)

Priorities – in CZ we have dStar DCS019V,  Fusion ROOM MORAVIA and DMR refl.4270(TS2,TG9) bridged as activity is lower and all people can meet at one place regardless of originating mode. We face issue where MMDVMHost receives three independent UDP streams, one from BM Master,one from irc ddb-gw and one from YSF-GW. It would be fantastic to select priorities, so DMR always wins or YSF wins etc. Where do I add this to feature request?
DTMF – option to force RPTR to mode, to reboot, etc.etc. All radios have DTMF. In case of need, or emergency, use DTMF to call script which selects different MMDVM.ini or changes eth0 default gw in case of planned downtime, etc.etc. Again. Where do i add feature request proposal?
LEDs – I think it speaks for itself….adding simple GPIO outputs HI / LO for each mode, so LEDs or relays can be driven?
Thanks gents. Have a great weekend.
73 Jiri OK2IT


From:  Jirka Culak <jiri.culak@outlook.com>
Date:  čtvrtek 20. října 2016 18:54
To:  g4klx/MMDVMHost <reply@reply.github.com>, g4klx/MMDVMHost <mmdvmhost@noreply.github.com>
Cc:  Mention <mention@noreply.github.com>
Subject:  Re: [g4klx/MMDVMHost] Error compiling Makefile.Pi.OLED (#178)

I am back now.i will test.

Jiří Čulák
Presales Engineer
FourteenIP EU - Czech republic
Tel +420 22888 0370
Mob +420 731 611577



On Thu, Oct 20, 2016 at 5:00 PM +0200, "Florian (DF2ET)" <notifications@github.com> wrote:

Fine for me as I have to be off to the club meeting then :-)

@ok2it Would you be able to test at least the Idle/CW Tx transition until then?

**Comment by ok2it** [comment]
I am back now.i will test.


Jiří Čulák

Presales Engineer

FourteenIP EU - Czech republic

Tel +420 22888 0370

Mob +420 731 611577






On Thu, Oct 20, 2016 at 5:00 PM +0200, "Florian (DF2ET)" <notifications@github.com> wrote:





Fine for me as I have to be off to the club meeting then :-)

@ok2it Would you be able to test at least the Idle/CW Tx transition until then?

**Comment by phl0** [comment]
So the extra "display.display()“ after cleardisplay is not needed?

**Comment by ok2it** [comment]
Ok latest commit from level works as expected, CW is displayed and screen cleaned…just funny bit, on original idle screen there is little… antenna icon…which isn’t there anymore after screen clear….lovely.
I think it looks more like T than antenna anyway when you use so small OLED like I do so for me its a feature.

Good work, I consider this as done and completed ready for major release.

Thanks again.

**Comment by phl0** [comment]
@ok2it Could you please provide some pics? And I guess it would be useful to open another issue for this to document because this one is closed already.

**Comment by ok2it** [comment]
It seems so. It's working Ok now.

I can give u SSH access or send u oled.cpp


Jiří Čulák

Presales Engineer

FourteenIP EU - Czech republic

Tel +420 22888 0370

Mob +420 731 611577



Od: Florian (DF2ET)

Odesláno: úterý, 25. 10. 8:35 odp.

Předmět: Re: [g4klx/MMDVMHost] Error compiling Makefile.Pi.OLED (#178)

Komu: g4klx/MMDVMHost

Kopie: ok2it, Mention



So the extra "display.display()“ after cleardisplay is not needed?

**Comment by phl0** [comment]
Please move to a new issue because this one is closed. I will look into that then.

**Comment by ok2it** [comment]
I am in Barcelona now. I will be back on Saturday morning. I thought about getting you access to SSH of raspberry with mmdvm on dvmega a oled and webcam sitting next to it so when I am away you can test.


I also might have spare oled.display somewhere.


J


Jiří Čulák

Presales Engineer

FourteenIP EU - Czech republic

Tel +420 22888 0370

Mob +420 731 611577






On Tue, Oct 25, 2016 at 11:24 PM +0200, "Florian (DF2ET)" <notifications@github.com> wrote:





@ok2it Could you please provide some pics? And I guess it would be useful to open another issue for this to document because this one is closed already.
